// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoClickController from "./auto-click_controller"
application.register("auto-click", AutoClickController)

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import Bridge__ButtonController from "./bridge/button_controller"
application.register("bridge--button", Bridge__ButtonController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import EventController from "./event_controller"
application.register("event", EventController)

import LazyLoadingController from "./lazy_loading_controller"
application.register("lazy-loading", LazyLoadingController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PreserveScrollController from "./preserve_scroll_controller"
application.register("preserve-scroll", PreserveScrollController)

import PronounsSelectController from "./pronouns_select_controller"
application.register("pronouns-select", PronounsSelectController)

import ScrollIntoViewController from "./scroll_into_view_controller"
application.register("scroll-into-view", ScrollIntoViewController)

import SplideController from "./splide_controller"
application.register("splide", SplideController)

import SpotlightSearchController from "./spotlight_search_controller"
application.register("spotlight-search", SpotlightSearchController)

import TabsController from "./tabs_controller"
application.register("tabs", TabsController)

import TalksNavigationController from "./talks_navigation_controller"
application.register("talks-navigation", TalksNavigationController)

import ToggableController from "./toggable_controller"
application.register("toggable", ToggableController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TopBannerController from "./top_banner_controller"
application.register("top-banner", TopBannerController)

import TransitionController from "./transition_controller"
application.register("transition", TransitionController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)

import ScrollController from "./scroll_controller"
application.register("scroll", ScrollController)

import ButtonController from "./bridge/button_controller"
application.register("bridge--button", ButtonController)
