// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import TransitionController from "./transition_controller"
application.register("transition", TransitionController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)

import PronounsSelectController from "./pronouns_select_controller"
application.register("pronouns-select", PronounsSelectController)
