// This file is auto-generated by ./bin/rails stimulus:manifest:update
// Run that command whenever you add a new controller or create them with
// ./bin/rails generate stimulus controllerName

import { application } from "./application"

import AutoSubmitController from "./auto_submit_controller"
application.register("auto-submit", AutoSubmitController)

import DropdownController from "./dropdown_controller"
application.register("dropdown", DropdownController)

import ModalController from "./modal_controller"
application.register("modal", ModalController)

import PreserveScrollController from "./preserve_scroll_controller"
application.register("preserve-scroll", PreserveScrollController)

import PronounsSelectController from "./pronouns_select_controller"
application.register("pronouns-select", PronounsSelectController)

import ScrollIntoViewController from "./scroll_into_view_controller"
application.register("scroll-into-view", ScrollIntoViewController)

import SplideController from "./splide_controller"
application.register("splide", SplideController)

import TooltipController from "./tooltip_controller"
application.register("tooltip", TooltipController)

import TransitionController from "./transition_controller"
application.register("transition", TransitionController)

import VideoPlayerController from "./video_player_controller"
application.register("video-player", VideoPlayerController)
