---
EnableDefaultLinters: true
glob: "**/*.{html}{+*,}.erb"
exclude:
  - vendor/bundle/**/*
  - node_modules/**/*
  - tmp/**/*
  - log/**/*

linters:
  ErbSafety:
    enabled: true
  PartialInstanceVariable:
    enabled: true
    exclude:
      - app/views/contributions/_events_without_videos.html.erb
      - app/views/contributions/_speakers_without_github.html.erb
      - app/views/contributions/_talks_without_slides.html.erb
      - app/views/contributions/_events_without_location.html.erb
      - app/views/contributions/_events_without_dates.html.erb
      - app/views/contributions/_talks_dates_out_of_bounds.html.erb
  Rubocop:
    enabled: true
    rubocop_config:
      require: standard
      inherit_gem:
        standard: config/base.yml
      Layout/InitialIndentation:
        Enabled: false
      Layout/TrailingEmptyLines:
        Enabled: false
      Lint/UselessAssignment:
        Enabled: false
