default: &default
  database: cache
  size_estimate_samples: 100
  store_options:
    max_age: <%= 30.days.to_i %>
    max_size: <%= 1.gigabytes %>
    namespace: <%= Rails.env %>
    expiry_method: :job
    expiry_queue: :low

development:
  <<: *default

test:
  <<: *default

staging:
  <<: *default

production:
  <<: *default
