# SQLite. Versions 3.8.0 and up are supported.
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem "sqlite3"
#
default: &default
  adapter: sqlite3
  pool: 20
  timeout: 5000

# DATABASE CONFIGURATIONS
primary: &primary
  <<: *default
  database: storage/<%= Rails.env %>_rubyvideo.sqlite3

cache: &cache
  <<: *default
  migrations_paths: db/cache_migrate
  database: storage/<%= Rails.env %>_rubyvideo-cache.sqlite3

queue: &queue
  <<: *default
  migrations_paths: db/queue_migrate
  database: storage/<%= Rails.env %>_rubyvideo-queue.sqlite3

development:
  primary: *primary
  cache: *cache
  queue: *queue

test:
  primary: *primary
  cache: *cache
  queue: *queue

staging:
  primary: *primary
  cache: *cache
  queue: *queue

production:
  primary: *primary
  cache: *cache
  queue: *queue
