default: &default
  database: cache
  store_options:
    max_age: <%= 1.month.to_i %>
    max_size: <%= 512.megabytes %>
    namespace: <%= Rails.env %>

development:
  <<: *default

test:
  <<: *default

production:
  <<: *default
